# Generated by Django 4.2 on 2023-11-18 22:25

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                max_length=11, unique=True, validators=[apps.utils.validators.NationalIdValidator()]
            ),
        ),
    ]
