# Generated by Django 4.2 on 2023-11-18 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("description", models.JSONField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("num_units", models.IntegerField()),
                ("architecturally_designed", models.BooleanField(default=True)),
                ("construction_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_state",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildingImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="building_images/")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="estates.building"
                    ),
                ),
            ],
            options={
                "verbose_name": "Building Image",
                "verbose_name_plural": "Building Images",
            },
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["id", "name", "location"], name="estates_bui_id_5edb5d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="building",
            unique_together={("name", "location")},
        ),
    ]
